### ISSUE TITLE
Vista detalle (ItemDetail) no renderiza el ItemCount, renderiza directamente el botón "Ir a carrito"

### ISSUE THREAD

**Issue by alexmarinmendez** [garrito182/ReactJS_Proyect#1]
En el componente ItemDetail, está mal declarado el estado itemCount:
la declaración debe ser: const [itemCount, setItemCount] = useState(0)
Es un destructuring de un array (no de un objeto como lo tienes actualmente)
Además, debes asignar el valor inicial del estado a CERO (actualmente no le asignas ningún valor)

Esto último es necesario para que el renderizado condicional que usas más abajo pueda funcionar.

Finalmente, debes setear el valor del estado cuando se ejecuta la función onAdd. Tu función onAdd debe quedar así:
`   
const onAdd = (count) => {

        if (count >= 1) {

            alert("Se agregaron " + count + " productos al carrito!");

            setItemCount(count)

        } else {

            alert("No se agregaron productos al carrito!");

        }

    }
`

Debes agregar el setItemCount en la sección true del condicional.

**Comment by garrito182** [comment]
Solucionado.
